services:

  arcane:
    image: ghcr.io/getarcaneapp/manager:latest
    container_name: arcane
    restart: unless-stopped
    ports:
      - "3552:3552"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./arcane-data:/app/data
      # Optional host project mount:
      # - /path/to/projects:/app/data/projects
    environment:
      - PUID=1000
      - PGID=1000
      - APP_URL=http://localhost:3552
      - ENCRYPTION_KEY=973f2d5193189c0c96d1b1d2d5cc6e406b9eaf7d3af82d6222f66e011364c107
    cgroup: host
